theme = "oceanic-next"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
end-of-line-diagnostics = "hint"

jump-label-alphabet = "abcdefghijklmnoprstuvwyz"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"
max-diagnostics = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "diagnostics", "selections", "position", "file-encoding", "file-line-ending"]

[keys.normal]
d = "delete_selection_noyank"

# Selection
I = "extend_char_right"
N = "extend_char_left"
W = "extend_next_word_start"
B = "extend_prev_word_start"

l = "goto_first_nonwhitespace"
y = "goto_line_end"

Y = "extend_to_line_end"
L = "extend_to_first_nonwhitespace"

C-tab = "goto_next_buffer"
C-S-tab = "goto_previous_buffer"
C-w = ":buffer-close"

j = "extend_line_below"

esc = ["collapse_selection", "keep_primary_selection"]

n = "move_char_left"
e = "move_visual_line_down"
i = "move_char_right"
u = "move_visual_line_up"
h = "yank"


q = ":reset-diff-change"

a = "undo"
z = "redo"

r = "flip_selections"

O = "goto_prev_diag"
o = "goto_next_diag"

R = "no_op"
J = "no_op"
k = "no_op"
Q = "no_op"
"/" = "no_op"

[keys.normal.backspace]
backspace = ":q"
w = ":w"
r = ":reload"
b = ":buffer-close"
c = ":q"

[keys.normal.backspace.f]
backspace = ":q!"
w = ":w!"
b = ":buffer-close!"
c = ":q!"

[keys.normal.m] # move & match
u = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
e = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.normal.f] # find
f = "search"
g = "global_search"
i = "search_next"
n = "search_prev"
s = ["search_selection", "search"]

[keys.normal.c] # change
h = "insert_mode"
n = "insert_at_line_start"
i = "insert_at_line_end"
r = "replace"
R = "replace_with_yanked"

u = "open_above"
e = "open_below"

l = "increment"
L = "decrement"

[keys.normal.c.c] # change case
p = [":pipe ccase -t pascal"]
u = [":pipe ccase -t upper"]
l = [":pipe ccase -t lower"]
c = [":pipe ccase -t camel"]
s = [":pipe ccase -t snake"]
k = [":pipe ccase -t kebab"]
t = [":pipe ccase -t title"]
o = [":pipe ccase -p sentence -d \" \""]

[keys.normal.space]
f = "file_picker_in_current_directory"
i = "select_textobject_inner"
I = "select_textobject_around"
h = "yank_joined_to_clipboard"

y = "no_op"
Y = "no_op"
g = "no_op"
F = "no_op"
"'" = "no_op"
j = "no_op"
R = "no_op"
A-c = "no_op"
"/" = "no_op"

[keys.normal.g]
u = "goto_last_change"
e = "goto_file_end"

l = "goto_prev_function"
y = "goto_next_function"

t = "goto_type_definition"

f = "jump_backward"
p = "jump_forward"

c = "find_next_char"
b = "find_prev_char"

j = "no_op"
h = "no_op"
m = "no_op"
n = "no_op"
s = "no_op"

[keys.normal.v]
e = "expand_selection"
s = "shrink_selection"

[keys.select.g]
c = "extend_next_char"
b = "extend_prev_char"
n = "extend_to_first_nonwhitespace"

g = "no_op"  
f = "no_op"
h = "no_op"
l = "no_op"
s = "no_op"
d = "no_op"
D = "no_op"
y = "no_op"
r = "no_op"
i = "no_op"
t = "no_op"
a = "no_op"
m = "no_op"
p = "no_op"
k = "no_op"
j = "no_op"
w = "no_op"
"." = "no_op"

