theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
d = "delete_selection_noyank"
N = ":buffer-previous"
I = ":buffer-next"

esc = ["collapse_selection", "keep_primary_selection"]

n = "move_char_left"
e = "move_visual_line_down"
i = "move_char_right"
u = "move_visual_line_up"
l = "goto_prev_function"
y = "goto_next_function"
h = "yank"

"?" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"&" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

z = "undo"
Z = "redo"

a = "no_op"
A = "no_op"
O = "no_op"
r = "no_op"
R = "no_op"
j = "no_op" 
J = "no_op"
C-w = "no_op"
o = "no_op"
k = "no_op"
q = "no_op"
Q = "no_op"

[keys.normal.c]
h = "insert_mode"
n = "insert_at_line_start"
i = "insert_at_line_end"
r = "replace"
R = "replace_with_yanked"

u = "open_above"
e = "open_below"

l = "increment"
L = "decrement"
c = "switch_case"

[keys.normal.t]
s = "hsplit"
v = "vsplit"
c = "wclose"

n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_right"
u = "jump_view_up"

N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_right"
U = "swap_view_up"

[keys.normal.space]
w = ":write"
f = "file_picker_in_current_directory"
F = "no_op"
"'" = "no_op"
j = "no_op"
R = "no_op"
i = "select_textobject_inner"
I = "select_textobject_around"
c = ":buffer-close"

h = "yank_joined_to_clipboard"
y = "no_op"
Y = "no_op"

[keys.normal.g]
u = "move_line_up"
n = "goto_line_start"
e = "move_line_down"
i = "goto_line_end"

[keys.select.g]
u = "extend_line_up"
n = "goto_line_start"
e = "extend_line_down"
i = "goto_line_end"

[keys.select]
d = "delete_selection_noyank"
c = "no_op"

n = "extend_char_left"
e = "extend_visual_line_down"
i = "extend_char_right"
u = "extend_visual_line_up"

h = "yank"
y = "no_op"

z = "undo"
Z = "redo"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-line-ending"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
