theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
d = "delete_selection_noyank"
N = "goto_previous_buffer"
I = "goto_next_buffer"

esc = ["collapse_selection", "keep_primary_selection"]

n = "move_char_left"
e = "move_visual_line_down"
i = "move_char_right"
u = "move_visual_line_up"
h = "yank"
j = "no_op"

l = "half_page_up"
y = "half_page_down"

a = "undo"
z = "redo"

r = "flip_selections"

O = "no_op"
R = "no_op"
J = "no_op"
C-w = "no_op"
k = "no_op"
Q = "no_op"

[keys.normal.q]
q = ":q"
Q = ":q!"
w = ":wq"
W = ":wq!"
r = ":reload"

[keys.normal.m] # move
u = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
e = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.normal.f] # find
f = "search"
i = "search_next"
n = "search_prev"
s = ["search_selection", "search"]
c = "find_next_char"
C = "find_prev_char"

[keys.normal.c] # change
h = "insert_mode"
n = "insert_at_line_start"
i = "insert_at_line_end"
r = "replace"
R = "replace_with_yanked"

u = "open_above"
e = "open_below"

l = "increment"
L = "decrement"

[keys.normal.c.c] # change case
p = [":pipe ccase -t pascal", "ensure_selections_forward", "delete_char_forward"]
u = [":pipe ccase -t upper", "ensure_selections_forward", "delete_char_forward"]
l = [":pipe ccase -t lower", "ensure_selections_forward", "delete_char_forward"]
c = [":pipe ccase -t camel", "ensure_selections_forward", "delete_char_forward"]
s = [":pipe ccase -t snake", "ensure_selections_forward", "delete_char_forward"]
k = [":pipe ccase -t kebab", "ensure_selections_forward", "delete_char_forward"]
t = [":pipe ccase -t title", "ensure_selections_forward", "delete_char_forward"]
o = [":pipe ccase -p sentence -d \" \"", "ensure_selections_forward", "delete_char_forward"]

[keys.normal.t] # tile
s = "hsplit"
v = "vsplit"
c = "wclose"

n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_right"
u = "jump_view_up"

N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_right"
U = "swap_view_up"

[keys.normal.space]
w = ":write"
f = "file_picker_in_current_directory"
i = "select_textobject_inner"
I = "select_textobject_around"
c = ":buffer-close"
h = "yank_joined_to_clipboard"

y = "no_op"
Y = "no_op"
g = "no_op"
F = "no_op"
"'" = "no_op"
j = "no_op"
R = "no_op"

[keys.select.space]
w = ":write"
f = "file_picker_in_current_directory"
i = "select_textobject_inner"
I = "select_textobject_around"
c = ":buffer-close"
h = "yank_joined_to_clipboard"

y = "no_op"
Y = "no_op"
g = "no_op"
F = "no_op"
"'" = "no_op"
j = "no_op"
R = "no_op"

[keys.normal.g]
u = "goto_last_change"
n = "goto_first_nonwhitespace"
e = "goto_file_end"
i = "goto_line_end"

l = "goto_prev_function"
y = "goto_next_function"

t = "goto_type_definition"
k = "goto_implementation"

f = "jump_backward"
c = "jump_forward"

j = "no_op"
h = "no_op"

b = "no_op"
m = "no_op"
p = "no_op"
s = "no_op"

[keys.select.g]
u = "extend_line_up"
n = "goto_line_start"
e = "extend_line_down"
i = "goto_line_end"

[keys.select.f] # find
f = "search"
i = "search_next"
n = "search_prev"
s = ["search_selection", "search"]
c = "find_next_char"
C = "find_prev_char"

[keys.select]
d = "delete_selection_noyank"
c = "no_op"

n = "extend_char_left"
e = "extend_visual_line_down"
i = "extend_char_right"
u = "extend_visual_line_up"

h = "yank"
y = "no_op"

z = "undo"
Z = "redo"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-line-ending"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
