font: 
  size: 12
  normal:
      family: DejaVuSansM Nerd Font Mono
      style: Regular

colors:
  primary:
    background: '0x282C34'
    foreground: '0xabb2bf'
    bright_foreground: '0xe6efff'

  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'

window:
  padding:
    x: 10
    y: 10

key_bindings:
  - { key: Back, mods: Control, chars: "\x1b\x7f" } # Delete word
