# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# this is executed when mouseless starts, e.g. useful for setting the keyboard layout
# startCommand: "setxkbmap de"

# the default speed for mouse movement and scrolling
baseMouseSpeed: 2000.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 300.0
mouseAccelerationCurve: 3.0
startMouseSpeed: 50.0

layers:
- name: initial
  bindings:
    space: tap-hold space ; toggle-layer mouse ; 200
      
- name: mouse
  passThrough: true
  bindings:
    space: layer mouse
    q: reload-config
    n: move -1  0
    i: move  1  0
    u: move  0 -1
    e: move  0  1
    c: space
    w: scroll up
    p: scroll down
    z: speed 0.3
    r: button left
    s: button middle
    t: button right
    o: leftctrl
    f: leftshift
    a: leftalt
