#!/bin/bash

mkdir -p /var/home/sofusa/.local/bin
curl -L https://github.com/DavHau/nix-portable/releases/latest/download/nix-portable-$(uname -m) > ~/.local/bin/nix-portable
chmod +x ~/.local/bin/nix-portable

cat > ~/.local/bin/nix-shell << 'EOF'
#! /bin/bash
export NP_RUNTIME=bwrap
nix-portable nix develop ~/dotfiles/nix
EOF

chmod +x ~/.local/bin/nix-shell
