#!/bin/bash
~/dotfiles/init/download_scripts
~/dotfiles/replace_config

toolbox create --image quay.io/toolbx-images/archlinux-toolbox:latest

rpm-ostree install alacritty langpacks-da wtype

echo "[Autologin]
User=sofusa
Session=sway" | sudo tee /etc/sddm.conf.d/autologin.conf
