#!/bin/bash

sudo curl https://packages.microsoft.com/keys/microsoft.asc -fsSL -o /etc/pki/rpm-gpg/microsoft.asc
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null

sudo wget -q \
  -O /etc/yum.repos.d/scottames-ghostty.repo \
  https://copr.fedorainfracloud.org/coprs/scottames/ghostty/repo/fedora-rawhide/scottames-ghostty-fedora-rawhide.repo

sudo wget -q \
  -O /etc/yum.repos.d/lihaohong-yazi.repo \
  https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-rawhide/lihaohong-yazi-fedora-rawhide.repo

sudo rpm-ostree reset
sudo rpm-ostree install \
  ghostty \
  niri swayidle mako swaybg \
  atuin fd-find ripgrep \
  sudo-rs uutils-coreutils \
  cowsay kitty \
  npm \
  azure-cli \
  gh \
  code \
  rustup \
  clang \
  yazi \
  alsa-lib-devel protobuf-devel \
  # rust-alsa-sys-devel rust-openssl-sys-devel \
