#!/bin/env bash

npm config set prefix ~/.npm

scripts/install-dotnet
brew bundle install
brew bundle cleanup --force

dotnet tool update --tool-path ~/.local/bin csharpier
dotnet tool update --tool-path ~/.local/bin roslyn-language-server --prerelease
dotnet tool update --tool-path ~/.local/bin dotnet-outdated-tool

# Other
wget -q -qO- https://aka.ms/install-artifacts-credprovider.sh | bash

# Bicep language server
wget -q https://github.com/Azure/bicep/releases/latest/download/bicep-langserver.zip
rm -rf ~/build/lib/bicep-langserver
unzip -qq bicep-langserver.zip -d ~/build/lib/bicep-langserver
echo -e "#!/usr/bin/env bash\nexec dotnet ~/build/lib/bicep-langserver/Bicep.LangServer.dll" > ~/.local/bin/bicep-langserver
chmod +x ~/build/bin/bicep-langserver
rm bicep-langserver.zip

