#!/bin/bash

# nix
wget -P ~/ https://github.com/noamraph/nixsa/releases/download/v0.2.0/nixsa-0.2.0-x86_64-linux.tar.xz
mkdir ~/nixsa
tar -xf ~/nixsa-0.2.0-x86_64-linux.tar.xz -C ~/

# copr
sudo wget -P /etc/yum.repos.d/ https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-rawhide/pgdev-ghostty-fedora-rawhide.repo
sudo wget -P /etc/yum.repos.d/ https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-rawhide/yalter-niri-fedora-rawhide.repo

# packages
rpm-ostree install ghostty niri rust-glib-sys-devel rust-gstreamer-devel
