articles = [
    "https://world.hey.com/dhh/dell-is-on-a-roll-with-the-xps-5a09a84e",
    "https://andrewkelley.me/post/dont-take-black-pill.html",
    "https://mitchellh.com/writing/everyone-should-know-simd",
    "https://mitchellh.com/writing/superlogical",
    "https://world.hey.com/dhh/i-m-sorry-dave-380ec27d",
]
