#!/bin/bash

for dir in ~/dotfiles/config/*/
do
    dir=${dir%/*}
    dir="${dir##*/}"
    rm -rf ~/.config/$dir
    cp -r ~/dotfiles/config/$dir ~/.config/
done

rm -rf ~/.omnisharp
cp -r ~/dotfiles/home/.omnisharp ~/

cp ~/dotfiles/config/starship.toml ~/.config/

if [ -f /run/.containerenv ]; then
    pkill autotiling-rs
    cp /usr/sbin/autotiling-rs ~/.local/bin
    flatpak-spawn --host swaymsg reload
fi
