"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[custom.jj]
ignore_timeout = true
symbol = ""
when = true
command = '''
jj root > /dev/null && jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    "",
    change_id.shortest(4),
    bookmarks,
    "|",
    concat(
      if(conflict, "💥"),
      if(divergent, "🚧"),
      if(hidden, "👻"),
      if(immutable, "🔒"),
    ),
    raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
    raw_escape_sequence("\x1b[1;32m") ++ if(description.first_line().len() == 0,
      "(no description set)",
      if(description.first_line().substr(0, 29) == description.first_line(),
        description.first_line(),
        description.first_line().substr(0, 29) ++ "…",
      )
    ) ++ raw_escape_sequence("\x1b[0m"),
  )
'
'''

[custom.jjstate]
when = "jj log"
command = '''
jj log -r@ -n1 --no-graph -T "" --stat | tail -n1 | sed 's/,.*//'
'''

[git_branch]
disabled =  true

[git_commit]
disabled =  true

[git_state]
disabled =  true

[git_status]
disabled =  true

[line_break]
disabled = true

[container]
disabled = true

[package]
disabled = true

[bun]
disabled = true

[buf]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[golang]
disabled = true

[gradle]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[opa]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[solidity]
disabled = true

[swift]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true

[nix_shell]
disabled = true
