hide-cursor-when-typing = true
confirm-before-quit = false

[fonts]
size = 18

[bindings]
keys = [
  { key = "tab", with = "control", action = "ReceiveChar" },
  { key = "tab", with = "control | shift", action = "ReceiveChar" },
  { key = "c", with = "control", action = "Copy" },
  { key = "v", with = "control", action = "Paste" }
]

[colors]
# Regular colors
background = '#1b2b34'
black = '#1b2b34'
blue = '#7198c8'
cyan = '#74b1b2'
foreground  = '#c0c5ce'
green = '#a2c699'
magenta = '#c594c5'
red = '#db686b'
white = '#d8dee9'
yellow = '#f2ca73'

# Cursor
cursor = '#d8dee9'
vi-cursor = '#d8dee9'

# Navigation
tabs = '#c0c5ce'
tabs-foreground = '#d8dee9'
tabs-active = '#7198c8'
tabs-active-highlight = '#74b1b2'
tabs-active-foreground = '#d8dee9'
bar = '#a7adba'

# Search
search-match-background = '#c0c5ce'
search-match-foreground = '#d8dee9'
search-focused-match-background = '#db686b'
search-focused-match-foreground = '#d8dee9'

# Selection
selection-foreground = '#d8dee9'
selection-background = '#c0c5ce'

# Dim colors
dim-black = '#1b2b34'
dim-blue = '#7198c8'
dim-cyan = '#74b1b2'
dim-foreground = '#d8dee9'
dim-green = '#a2c699'
dim-magenta = '#c594c5'
dim-red = '#db686b'
dim-white = '#d8dee9'
dim-yellow = '#f2ca73'

# Light colors
light-black = '#1b2b34'
light-blue = '#7198c8'
light-cyan = '#74b1b2'
light-foreground = '#c0c5ce'
light-green = '#a2c699'
light-magenta = '#c594c5'
light-red = '#db686b'
light-white = '#d8dee9'
light-yellow = '#f2ca73'
