#!/bin/bash

power_off=' Power off'
reboot=' Reboot'
lock=' Lock'
suspend='󰤄 Suspend'
log_out=' Log out'

options="${lock}\n${power_off}\n${reboot}\n${suspend}\n${log_out}"
chosen=$(echo -e "$options" | fuzzel --dmenu --prompt=" ")

case "$chosen" in
    ${lock})
        swaylock
        ;;
    ${power_off})
        systemctl poweroff
        ;;
    ${reboot})
        systemctl reboot
        ;;
    ${suspend})
        systemctl suspend
        ;;
    ${log_out})
        niri msg action quit --skip-confirmation
        ;;
    *)
        ;;
esac

