[colors]
ansi = [
  '#1e2127',
  '#e06c75',
  '#98c379',
  '#d19a66',
  '#61afef',
  '#c678dd',
  '#56b6c2',
  '#abb2bf',
]
background = "#282c34"
brights = [
  '#5c6370',
  '#e06c75',
  '#98c379',
  '#d19a66',
  '#61afef',
  '#c678dd',
  '#56b6c2',
  '#ffffff',
]
cursor_bg = "#ABB2BF"
cursor_fg = "#282c34"
cursor_border = "#abb2bf"
foreground = "#abb2bf"
selection_bg = "#ABB2BF"
selection_fg = "#282c34"

[colors.tab_bar]
inactive_tab_edge = "#282c34"
background = "#282c34"

[colors.tab_bar.active_tab]
fg_color = "#c678dd"
bg_color = "#282c34"

[colors.tab_bar.inactive_tab]
fg_color = "#5c6370"
bg_color = "#282c34"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c678dd"
bg_color = "#282c34"

[colors.tab_bar.new_tab]
fg_color = "#c678dd"
bg_color = "#282c34"

[colors.tab_bar.new_tab_hover]
fg_color = "#282c34"
bg_color = "#c678dd"

[colors.indexed]
59 = "#5c6370"
100 = "#e2be7d"
214 = "#d19a66"

[metadata]
name = "onedarkpro_onedark"
